RequireFiles("Shared/Helpers/", {
    "Constants",
    "VC/_Init",
    "Enums/_Init",
    "PresetCompat",
    "ModValidation",
    "Table",
    "Printer",
    "UserData",
    "CCA",
    "JsonLayer",
    "UserID",
    "ValueSerializer",
    "LocalizationManager",
    "ResourceHelper",
})
